### ISSUE TITLE
mybatis-3.4.5-JSON.jar

### ISSUE THREAD

**Issue by lerry903** [tianhao/mybatis-JsonTypeHandler#1]
能提供一下mybatis-3.4.5-JSON.jar这个包的来源吗？

**Comment by tianhao** [comment]
https://github.com/tianhao/mybatis-3/tree/json-support ,json-support 分支是我改 mybatis-3 源码支持 json 读写的，你要自已编译一下，另外需要 在 application.yml 中添加 `default-json-type-handler: com.tianhaox.mybatis.type.FastJsonTypeHandler` 配置指定jsonHandler类。
本 repo 用的是 postgresql 数据库，如果是其它数据库，要稍微改下

**Comment by lerry903** [comment]
thx
